//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDName
    {
        public int MDNameIDPK { get; set; }
        public string MDName1 { get; set; }
        public Nullable<int> MedicalDeviceCategoryIDFK { get; set; }
        public Nullable<System.DateTime> added_on { get; set; }
        public Nullable<decimal> added_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<decimal> modified_by { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string MDName_Ar { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
